### ISSUE TITLE
Setup Firebase sites

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#2]
## Firebase

Ready to setup the Firebase infrastructure. Thinking something as follows:

- PRs are created and a Firebase preview site is created for the PR. Here we use the same site naming conventions as in the past.
- PR is merged to `main`, this triggers a **stage** Firebase site update to `stage-api3-docs.web.app`.
- A PR is created to merge `main` to `live-site`, this triggers a **production** Firebase site update to `api3-docs.web.app`.

## Site names

- PR previews: Same as api3-docs is using
- Stage: `stage-api3-docs.web.app`.  This name is nice because when typing stage first (into the browser) URL bar, you will most like get the stage site as the first recommendation.
- Production: `api3-docs.web.app`, cause it makes sense.

## Notes & Concerns

- There may be code in Firebase files from `api3-docs` that I have not moved over into `vitepress-docs`.
- What Firebase project will this go into?
- Can more than one person have access to the Firebase project?

**Comment by dcroote** [comment]
Moving to done as we've been using the deployments successfully. @wkande feel free to reopen if you feel otherwise.
