### ISSUE TITLE
`authorizers.crossChainRequesterAuthorizers` poorly documented

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#211]
See `reference/airnode/latest/understand/apply-auth.html`
and
`/reference/airnode/latest/concepts/authorizers.html`

**Comment by dcroote** [comment]
Cross-chain authorizers are documented in the v0.10 docs, see https://github.com/api3dao/api3-docs/pull/1101

**Comment by wkande** [comment]
This has been migrated.
