### ISSUE TITLE
Quick start container tutorial: testing explanation

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#383]
Need to explain that the testing gateway by-passes the blockchain.

> There was a guy on discord who followed the [container quick guide](https://docs.api3.org/airnode/v0.8/grp-providers/tutorial/quick-deploy-container/) and then tried to do [RRP flow](https://docs.api3.org/airnode/v0.8/grp-developers/call-an-airnode.html). The testing gateway worked for him, but the RRP flow didn’t and he got an error because his Infura required an API key. Some findings:
He didn’t understand that testing gateway is avoiding blockchain (he was surprised why RRP doesn’t work when testing gateway does)
He hasn’t checked Airnode errors and didn’t know what was the problem
The easy fix is to uncheck the “require API key” in infura settings
Sharing also for others to know in case there is someone with the same problem.
Also, we could be a bit more explicit about “what” is happening in the quick guides (at least mention the testing gateway docs).

**Comment by wkande** [comment]
Could we simply move the reader to another guide such as **Making an RRP Request**. The quick deploy tutorials are all about getting an Airnode up and running quickly, nothing more. 

@Ashar2shahid what do you think?

**Comment by Ashar2shahid** [comment]
Yeah, I found it slightly weird too. We still need a way to test the deployment but I think the gateway can be a separate tutorial in of itself

**Comment by wkande** [comment]
The tutorial does test the deployment using the gateway and I think it is fine as it is. Emanuel was talking to a reader that wanted to make an RRP request using their newly created Airnode. That would be overkill in this tutorial. So I was thinking to mention RRP and link the user to another guide.

**Comment by wkande** [comment]
This tutorial has been updated to route the user to the RRP call guide.
