### ISSUE TITLE
Parse GCP project ID from `gcp.json` instead of `config.json`

### ISSUE THREAD

**Issue by aquarat** [api3dao/vitepress-docs#385]
Documentation for https://github.com/api3dao/airnode/issues/1317

**Comment by wkande** [comment]
@dcroote What should we do with this one. If not part of `v0.12` should we tag it `v0.13`?

**Comment by dcroote** [comment]
Right now the corresponding Airnode issue [is marked v0.13](https://github.com/api3dao/airnode/milestone/16), but that may change soon

**Comment by dcroote** [comment]
I've moved it to [milestone](https://github.com/api3dao/airnode/milestones) 0.14.0

**Comment by dcroote** [comment]
Closing to clear older Airnode-related issues from the docs. Can reopen if work on the corresponding Airnode issue resumes.
