### ISSUE TITLE
Single Lambda Airnode

### ISSUE THREAD

**Issue by amarthadan** [api3dao/vitepress-docs#388]
Documentation for https://github.com/api3dao/airnode/issues/1478

**Comment by wkande** [comment]
@dcroote  Should we tag this issue as `v0.14`?

**Comment by dcroote** [comment]
It's already tagged as v0.14, no?

**Comment by wkande** [comment]
Actually I meant using the Label v0.14 attached to this issue directly.  I do see now that it is in the Airnode documentation tracker.

**Comment by dcroote** [comment]
I think historically we've only labeled the Airnode issues themselves and have had the associated docs issue's version tracked by the documentation tracker

**Comment by dcroote** [comment]
Closing to clear older Airnode-related issues from the docs. Can reopen if work on the corresponding Airnode issue resumes.
