### ISSUE TITLE
Simplify the overrides in admin CLI due to EIP1559

### ISSUE THREAD

**Issue by amarthadan** [api3dao/vitepress-docs#389]
Documentation for https://github.com/api3dao/airnode/issues/1506

**Comment by wkande** [comment]
@dcroote Should this issue be tagged for Airnode `v0.14`?

**Comment by dcroote** [comment]
Same comment as https://github.com/api3dao/vitepress-docs/issues/388#issuecomment-1793608499

**Comment by dcroote** [comment]
Closing to clear older Airnode-related issues from the docs. Can reopen if work on the corresponding Airnode issue resumes.
