### ISSUE TITLE
Document TTL/persistence around endpoint response caching

### ISSUE THREAD

**Issue by aquarat** [api3dao/vitepress-docs#393]
As per https://api3workspace.slack.com/archives/C02R79STBRA/p1663088756057769
the timeouts/TTL for cache entries for different execution environments should be documented. This will need some research. 

I know from previous experience and testing the Lambda is up to 2.5 hours.
"Traditional" Docker  environments will be much longer.
GCP is unknown.

**Comment by wkande** [comment]
@aquarat @Siegrift 

This issue is somewhat old and I would like to move it along. However we need someone that understands it to give it a go. As Emanuel said:
> It is better if this is documented by some dev.

I really do not understand it at all. I could try if someone had the time to explain it all to me in detail. That would take a Slack huddle as back and forth using DM on this one would be difficult.

**Comment by aquarat** [comment]
Looking at this, I think my original post from October is most of the information required - it just needs to be formatted for the documentation site. I don't think this needs testing/it's not a good enough ROI to warrant testing it.

An alternative way of describing what's going on:

Airnode has the ability to cache API responses, per request ID to the local filesystem. This only applies to blockchain requests.

The flow is:
1. A request is received from the Blockchain
2. The Airnode does an HTTP/S call to a remote API based on the request
3. [with caching enabled] Airnode stores the response locally, in the local filesystem, per request ID.
4. Airnode then follows the usual process of extracting the response, post-processing it and sending the response back on chain.

The Airnode then exits... until the next cycle (the next minute).
If, during the next cycle, the Airnode gets the same request and it isn't fulfilled, it'll try and fulfill the request again.

Ordinarily, it would follow steps 1, 2 and 4 without caching enabled, but with caching enabled it'll read the previous API response value from the local filesystem and send that back to the chain.

The above is useful for two main use-cases:
1. "Non-idempotent" operations; eg. an endpoint called `https://acme.cool/toggle` - you probably wouldn't want something to be toggled multiple times from one request (repeated fulfillment attempts over multiple cycles)
2. Random Numbers; a malicious blockchain provider can selectively block fulfillments containing numbers they don't like, allowing them to improve their odds of winning in a random-number betting game, as an example.

That's caching.

The problem with Airnode's local caching implementation is that it relies on the local filesystem. If the local filesystem is cleared, the cache is lost and if a repeat request is received after the cache has been cleared, Airnode will contact the remote API again. Airnode self-clears cached data after the data has reached 1 hour's age.

The local filesystem cache clearance is a product of the environment Airnode runs in.

As a guideline:
- AWS Lambda persists for 2.5 hours
- Google Cloud persists for between 1 and 24 hours
- Docker persists as long as the container remains running 

The above is a guideline: 
- API3 won't guarantee this
- users should test themselves if it's important to them
- if request caching is mission critical Airnode should be run in a Docker container with a persistent `/tmp` directory

Furthermore, as an example: if an Airnode Lambda environment/container has been "warm" for 2.4 hours and AIrnode gets a request, that request will only be cached until the container resets, in this case 2.5 hours - 2.4 hours = 0.1 hours remaining to the environment being cleared.

It's important that the docs make it clear that the endpoint caching on serverless infrastructure is unreliable and best effort.

**Comment by wkande** [comment]
@aquarat 

> The Airnode then exits... until the next cycle (the next minute).
> If, during the next cycle, the Airnode gets the same request and it isn't fulfilled, it'll try and fulfill the request again.

Tries to fulfill it again from cache that was established on a previous run cycle? If the requestID is not cached it goes back to the API Provider?

**Comment by dcroote** [comment]
Closed by https://github.com/api3dao/vitepress-docs/pull/475
