### ISSUE TITLE
Include additional statistical data in the heartbeat payload

### ISSUE THREAD

**Issue by aTeoke** [api3dao/vitepress-docs#398]
Documentation for task [#1339](https://github.com/api3dao/airnode/issues/1339)

**Comment by aTeoke** [comment]
oh sorry, I missed this. @wkande so far no, because the issue this is documentation for has not been completed yet

**Comment by wkande** [comment]
@dcroote I'm not sure what this is anymore. Do you think this is still needed?

**Comment by dcroote** [comment]
The corresponding Airnode issue is still open so probably easiest to leave it open

**Comment by dcroote** [comment]
Closing to clear older Airnode-related issues from the docs. Can reopen if work on the corresponding Airnode issue resumes.
