### ISSUE TITLE
Allow opening links in a new tab from search bar

### ISSUE THREAD

**Issue by Siegrift** [api3dao/vitepress-docs#403]
AS of now, you are not able to open stuff from the search panel in a new tab. Both:
1) right click + open in new tab context menu
2) ctrl + click

don't work.

**Comment by wkande** [comment]
This is now working in `vitepress-docs`.
<img width="376" alt="Screenshot 2023-04-13 at 2 03 27 PM" src="https://user-images.githubusercontent.com/3522283/231870715-04baccf0-6542-452c-b7ee-4cb2f1283855.png">
