### ISSUE TITLE
Describe HTTP signed data gateway signing and signature recovery processes

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#496]
A [user on Discord noted](https://discord.com/channels/758003776174030948/1096629188397637733/1114144755195052074) that [we do not explain](https://docs.api3.org/reference/airnode/latest/understand/http-gateways.html#http-signed-data-gateway) how the HTTP signed data gateway signs the data nor how to verify the signature on-chain.

@Ashar2shahid provided the following links to the Airnode repo:

- https://github.com/api3dao/airnode/blob/32afa71f0f20dc2297d66c223d57c01a00c1acd4/packages/airnode-node/src/api/index.ts#LL261C8-L261C8
- https://github.com/api3dao/airnode/blob/32afa71f0f20dc2297d66c223d57c01a00c1acd4/packages/airnode-node/src/api/index.ts#L92
- https://github.com/api3dao/airnode/blob/32afa71f0f20dc2297d66c223d57c01a00c1acd4/packages/airnode-protocol/contracts/rrp/AirnodeRrpV0.sol#L245-L251

**Comment by wkande** [comment]
@dcroote Shall we close this one?
