### ISSUE TITLE
Bump Airnode version to v0.11.2

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#528]
Release: https://github.com/api3dao/airnode/releases/tag/v0.11.2

Note this version uses OIS v2.1.0

**Comment by wkande** [comment]
@dcroote - Can I do this tomorrow (Thursday)?

**Comment by wkande** [comment]
@dcroote - Does the migration guide for `v0.11.x` change as well?

**Comment by dcroote** [comment]
@wkande - yes thanks for the reminder, I opened https://github.com/api3dao/vitepress-docs/pull/529
