### ISSUE TITLE
Adding of issue template

### ISSUE THREAD

**Issue by KenCarvAPI** [api3dao/vitepress-docs#542]
Could we add the below as a template for a docs feedback form
---
## Context
< Please provide some background about why you’re providing this feedback. This could include things like a brief description of what you were trying to do or what part of the codebase your feedback is related to. >

## Suggested Changes
< If you have any suggestions for how we could improve based on your feedback, please describe them here. This could include things like changes to the code, new features, updates to the documentation, etc. >

## Additional Information
< If there’s anything else you want to add, you can do that here. This could include things like code samples, screenshots, etc. >

---

**Comment by dcroote** [comment]
The template has been implemented and can be viewed by [creating an issue](https://github.com/api3dao/vitepress-docs/issues/new).
