### ISSUE TITLE
Simple guide on how to verify Airnode addresses

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#548]
## Context
Jiri has requested a short guide on how a dAPP owner can verify the addresss of an API provider's Airnode.

## Suggested Changes
A new guide

## Additional Information
For these API providers:

- Coinpaprika: https://coinpaprika.com/
- dxfeed: https://dxfeed.com/
- Finage: https://finage.co.uk/
- Finnhub: https://finnhub.io/
- Kaiko: https://www.kaiko.com/
- NewChangeFX: https://www.newchangefx.com/
- Nodary: https://nodary.io/docs/data-feeds/
- TraderMade: https://tradermade.com/
- twelvedata: https://twelvedata.com/

An example link"
https://www.digitalocean.com/community/tools/dns?domain=dxfeed.com#TXT-Records

There is issue in that the provider's used ChainAPI and as such there `txt` record will use the following:
```
dxfeed.com | 86400 | chainapi-verification-keys=[0x11030d4f8eB06F958E763C6f8b165D7CDd98DB6C]
```

So advise the reader to look for `chainapi-verification-keys=` in the provider's `txt` records.

Note from Jiri:
Hi Warren, I talked with Burak about this and he said, that it's not really correct, but with ChainAPI winding down, we should not really ask them to do any changes. So he suggested we just explain in the docs, that the user should search for: chainapi-verification-keys in order to find the airnode address.

**Comment by wkande** [comment]
Waiting on Jiri to verify an issue with Kaiko's DNS `TXT` record. It does not seem to exist.

**Comment by wkande** [comment]
Jiri has contacted Kaiko and they are getting the txt record added.

**Comment by Ashar2shahid** [comment]
Seems like this is done, if so we can close this

**Comment by dcroote** [comment]
My guess is that this was left open because kaiko didn't have a txt record present. I just checked and that's still the case.

**Comment by wkande** [comment]
Pretty sure the txt record is all set.

**Comment by dcroote** [comment]
I don't see it [here](https://www.digitalocean.com/community/tools/dns?domain=kaiko.com#TXT-Records) whereas it is for others, e.g. nodary, [here](https://www.digitalocean.com/community/tools/dns?domain=nodary.io#TXT-Records).

**Comment by wkande** [comment]
nodary.io | 300 | chainapi-verification-keys=[0xc52EeA00154B4fF1EbbF8Ba39FDe37F1AC3B9Fd4] Show less...
-- | -- | --

**Comment by dcroote** [comment]
@wkande please reread all of the comments

**Comment by wkande** [comment]
Wellit was there when Jiri and I dod this. Now I need to track it down again.

**Comment by wkande** [comment]
Moved her so I will fix this.
https://www.digitalocean.com/community/tools/dns?domain=kaiko.io#TXT-Records
