### ISSUE TITLE
Broken guide zip files

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#561]
[Discord user](https://discord.com/channels/758003776174030948/1096629188397637733/1130894026040688640) was initially first to report, with assistance from @vanshwassan. I've gone through the guide zip files and found the following issues:

- [Deploying on GCP guide](https://docs.api3.org/guides/airnode/deploy-airnode/deploy-gcp/)
  - Wrong `nodeVersion` in `config.json` (current value is `2`, should be `0.11.2`)
- [Deploying locally guide](https://docs.api3.org/guides/airnode/deploy-airnode/deploy-container/)
  - This looks like the wrong files got uploaded as this is the `gcp` config and secrets file, not the local config e.g. `type` is `gcp`, there is `${PROJECT_ID}` present (which only applies to GCP),  `secrets.env` should not have `PROJECT_ID`, etc.
  - Wrong `nodeVersion` as above 
  - The config JSON and secrets.env that is embedded / collapsible in the page looks right though
- AWS guide zip files look OK

**Comment by wkande** [comment]
@dcroote @vanshwassan -  I will get this fixed this morning,

**Comment by dcroote** [comment]
Closed by https://github.com/api3dao/vitepress-docs/pull/562
