### ISSUE TITLE
Airnode reference version selection is invisible in dark mode

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#573]
On desktop. Confirmed with 2 browsers (Chrome and Edge) on Windows.

Dark mode:

![image](https://github.com/api3dao/vitepress-docs/assets/13989647/5f5d8b09-25c1-43d4-916c-ea54cecee9ff)

Light mode:

![image](https://github.com/api3dao/vitepress-docs/assets/13989647/f5f8ce3c-30c5-4bda-a12f-44e7c83fb854)

**Comment by wkande** [comment]
@dcroote - I am getting the text in my overlay. I'm wondering if this is a Windows thing. @Ashar2shahid @vanshwassan can you check this out, I believe you are on Windows.


<img width="309" alt="Screenshot 2023-07-27 at 1 23 38 AM" src="https://github.com/api3dao/vitepress-docs/assets/3522283/6ac10c6f-0ba0-4335-a06f-2ad4896beac2">

**Comment by wkande** [comment]
Code here: https://github.com/api3dao/vitepress-docs/blob/main/docs/_components/reference/VersionPicklist.vue

**Comment by dcroote** [comment]
@wkande - correct, I've updated my original comment
