### ISSUE TITLE
USDC affix zeros for proposals

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#606]
Should this say add 6 zero digits to a dollar value excluding the cents? And of course 4 zeros when cents are present represented by 2 digits.
`$299     = 299000000`
`$299.50  = 299500000`
`$299.99  = 299990000`

>  Precision
> USDC uses 6 decimal places of precision as opposed to 18 that many other ERC20 tokens use. Add 6 zeros after the amount you are asking for.

**Comment by dcroote** [comment]
I think the "adding zeros" aspect is where it's confusing, particularly for values that include cents. What about:

USDC uses 6 decimal places of precision as opposed to 18 that many other ERC20 tokens use. Consequently, multiply the desired $USD by 10^6 to get the USDC amount to enter e.g. USD$299 -> 299000000.
