### ISSUE TITLE
"Templates" files are redundant with "Examples" files

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#620]
All of the Airnode Templates files ([config.json](https://docs.api3.org/reference/airnode/latest/deployment-files/templates/config-json.html), [secrets.env](https://docs.api3.org/reference/airnode/latest/deployment-files/templates/secrets-env.html), and [aws.env](https://docs.api3.org/reference/airnode/latest/deployment-files/templates/aws-env.html)) are near perfect copies of their Examples counterparts ([config.json](https://docs.api3.org/reference/airnode/latest/deployment-files/examples/config-json.html), [secrets.env](https://docs.api3.org/reference/airnode/latest/deployment-files/examples/secrets-env.html), and [aws.env](https://docs.api3.org/reference/airnode/latest/deployment-files/examples/aws-env.html)), but are much less useful because the values for everything are just some variation of `<FILL_*>`, requiring someone to look at the Examples files or the appropriate Reference e.g. [config.json](https://docs.api3.org/reference/airnode/latest/deployment-files/config-json.html) to figure out what to do.

I therefore propose deleting all of these Templates files ("don't repeat yourself").

**Comment by dcroote** [comment]
@wkande what do you think?

**Comment by wkande** [comment]
@dcroote Do we still want to pursue this?

**Comment by dcroote** [comment]
I would say it's very low priority. I'm fine with closing if you'd like.

**Comment by dcroote** [comment]
Closing as low priority
