### ISSUE TITLE
Release Airnode v0.13 and OIS v2.2.1 doc sets

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#643]
Airnode v0.13 release is upcoming, while OIS v2.2.1 [is already released](https://github.com/api3dao/ois/releases/tag/v2.2.1).

**Comment by wkande** [comment]
@dcroote Let me know when ready. I will set up the versioning and such.

**Comment by dcroote** [comment]
@wkande - Airnode v0.13 has been released and tested (https://github.com/api3dao/airnode/issues/1900) so we're ready to release these doc sets

**Comment by wkande** [comment]
@dcroote I will get started on this right after I merge the PR for the framework update. Can you take a look at that PR first?

**Comment by wkande** [comment]
@dcroote Also what do you want to do about `/next`. Hold off or do you have new version numbers for `/arinode` and `/ois`?
