### ISSUE TITLE
POA Network Sokol testnet missing from api3dao/chains

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#644]
There is a problem in [this](https://docs.api3.org/reference/qrng/chains.html#nodary) page. The page uses `@api3/chains` and `@api3/chains` does not export any chain with id `77`.

![image](https://github.com/api3dao/vitepress-docs/assets/46991761/d1f1a1df-4873-4137-9274-a765bd7a4044)

_Originally posted by @metobom in https://github.com/api3dao/vitepress-docs/issues/641#issuecomment-1752967217_

Rather than adding to api3dao/chains, I think it makes more sense to remove it from the table given [POA merged with gnosis chain](https://www.poa.network/) and this testnet [hasn't had a block in 10 months](https://blockscout.com/poa/sokol/).

**Comment by wkande** [comment]
@dcroote I just checked and the latest release of @API3/chains (`3.5.1`) does not contain Sokol.
<img width="451" alt="Screenshot 2023-10-10 at 5 28 34 AM" src="https://github.com/api3dao/vitepress-docs/assets/3522283/55c1aa2d-e391-42ae-aa74-45401c86a45c">
