### ISSUE TITLE
Consider upgrading from Node.js 18 to Node.js 20

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#674]
Rationale: Slack [discussion](https://api3workspace.slack.com/archives/C01N6001YCE/p1700771710567119) and Node.js [end of life timeline](https://endoflife.date/nodejs).

It looks like Node.js 20 should work with VitePress according to the [prerequisites](https://vitepress.dev/guide/getting-started#prerequisites): "Node.js version 18 or higher."

**Comment by wkande** [comment]
Sounds good. I will do this soon and update to Vitepress to the latest release (now @1.0.0-rc.31 (2023-11-25)) which inherits the following breaking change from a previous version. I do not see any issue with it.

> BREAKING CHANGES
> VitePress now uses shikiji instead of shiki for syntax highlighting. If you're using features like adding extra languages or custom aliases, please refer [shikiji docs](https://github.com/antfu/shikiji) for migration guide or comment on https://github.com/vuejs/vitepress/pull/3237 if you need help.
