### ISSUE TITLE
Remove `RequesterAuthorizerWithErc721` from docs

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#681]
See PR **[680](https://github.com/api3dao/vitepress-docs/pull/680)**

I was told that the contract `RequesterAuthorizerWithErc721` should be removed from the docs as it is not used. I do want @dcroote 's opinion to verify before we do this.  Which is why I did not include the removal with PR 680.

**Comment by wkande** [comment]
From Burak just now in Slack. 
> 
The thing with `RequesterAuthorizerWithErc721` is that it's supposed to be used through ChainAPI and ChainAPI didn't launch that feature yet. Also, there was a vulnerability on that contract, so I removed the old deployments from the package (which were never used anyway). So it will come back at some point, but not very soon.

This is an important point so we may want to archive the two pages that discuss `RequesterAuthorizerWithErc721` since it may come back to life on day.

**Comment by dcroote** [comment]
If you'd like I can take this since I worked with those docs pages e.g. in https://github.com/api3dao/vitepress-docs/pull/491
