### ISSUE TITLE
Error when running QRNG remix example

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#693]
A user reported [an error on Discord](https://discord.com/channels/758003776174030948/1062910245569040396/1195640053402181693), copied below:

I get the following error when trying to compelte this tutorial: https://docs.api3.org/guides/qrng/qrng-remix/ 

```
TypeError: Contract "QrngExample" should be marked as abstract.
 --> raw.githubusercontent.com/api3-ecosystem/remix-contracts/master/contracts/QrngRequesterUpdated.sol:7:1:
  |
7 | contract QrngExample is RrpRequesterV0, Ownable {
  | ^ (Relevant source part starts here and spans across multiple lines).
Note: Missing implementation: 
  --> @openzeppelin/contracts/access/Ownable.sol:38:5:
   |
38 |     constructor(address initialOwner) {
   |     ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by dcroote** [comment]
I've not tested, but [this answer](https://discord.com/channels/758003776174030948/1096629188397637733/1195744767116578856) sounds very plausible:

> Hey <@713758067581386803>  what version of solidity are you using.  I would try 0.8.19 or below and make sure to user the Openzepplin version 4 as 5 has changes.  You can do this with like this:
```import "@openzeppelin/contracts@4.9.5/access/Ownable.sol";```

**Comment by vanshwassan** [comment]
I've found another workaround, cloning the [`airnode-protocol-v1`](https://github.com/api3dao/airnode-protocol-v1) into a Remix Workspace and then importing the contracts works just fine.
![image](https://github.com/api3dao/vitepress-docs/assets/17065256/07d777b2-e593-4af6-bc4a-8eee29c1ef82)

**Comment by dcroote** [comment]
> I've found another workaround

Nice, though one way or another the docs should probably be updated?

**Comment by vanshwassan** [comment]
> Nice, though one way or another the docs should probably be updated?

Yeah, I'm assigning the issue to myself. I will update the sections.
