### ISSUE TITLE
Docs Airnode v0.14 release

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#698]
No new OIS docs release is necessary as Airnode 0.14 will be released with OIS 2.3.1, which is [already the latest](https://docs.api3.org/reference/ois/latest/versions.html).

**Comment by dcroote** [comment]
@wkande for your awareness my plan is to release Airnode this weekend, tracking here: https://github.com/api3dao/airnode/issues/1935

**Comment by wkande** [comment]
OK then. I will get started on this today. Not sure it will get deployed until tomorrow.
