### ISSUE TITLE
Finalize repo QA compliance

### ISSUE THREAD

**Issue by BTT21000** [api3dao/vitepress-docs#712]
As part of the TM issue https://github.com/api3dao/tasks/issues/849 for QA, some requirements need to be addressed:

### Repo setup requirements as per [new_repo_creation_checklist.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/new_repo_creation_checklist.md):
- [x] ~Add standard configuration files (e.g. eslint) as per standard requirements and other repositories.~ Prettier is the main linter given this repo is mostly markdown
- [x] Add the relevant license file (LICENSE.md) consistent with the organizational standards or project requirements.
- [x] If applicable, install Renovate in the repository, following the guidelines outlined in [dependencyManagementStrategy.md](https://github.com/api3dao/tasks/blob/main/Technical%20management/Tasks%20documentation/dependencyManagementStrategy.md).
- [x] If applicable, create/review renovate.json configuration file in the root of the repository to manage dependencies effectively, as per our dependency management strategy.
- [x] If applicable, set up Renovate for automated security vulnerability scanning to detect vulnerabilities in the codebase.

**Comment by dcroote** [comment]
Would you be able to add Renovate here too @andreogle ?

**Comment by andreogle** [comment]
Done 👍🏻

**Comment by dcroote** [comment]
Thanks!
