### ISSUE TITLE
Pre/Post Processing V2 clarification

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#715]
The following V1 post-processing works just fine:
```json
"postProcessingSpecifications": [
  {
    "environment": "Node",
    "timeoutMs": 5000,
    "value": "output = {myVal: 1}"
  }
],
```

and based on the [V2 input / output docs](https://docs.api3.org/reference/ois/latest/processing.html#input-and-output-1) "The output of the post-processing snippet is an object with the following properties: `response`...", I expected the following to work:
```json
"postProcessingSpecificationV2": {
  "environment": "Node",
  "timeoutMs": 5000,
  "value": "{response: {myVal: 5}}"
},
```

but this returns the very cryptic error:
```
TypeError: {(intermediate value)} is not a function 
```

It turns out, because of how `unsafeEvaluateV2 ` [works](https://github.com/api3dao/commons/blob/6e69a9186c70930a9ae041c166d62deaa3af65c6/src/processing/unsafe-evaluate.ts#L124-L126):
```
(async () => {
  return await (${code})(payload)
})();
```

it appears the correct post processing V2 snippet has to be:
```json
"value": "({ response }) => { return { response: {myVal: 5}}; }"
```

This could be much better explained.

**Comment by dcroote** [comment]
Also the `value` fields in all OIS V2 processing-related tests would error. If those are just placeholders, which is fine, it should be clearer.

https://github.com/api3dao/ois/blob/0235bdd5654a8561776f874474705538f23a1b50/src/ois.test.ts#L710-L807

**Comment by Siegrift** [comment]
Mhh, the [documentation](https://docs.api3.org/reference/ois/latest/processing.html#input-and-output-1) says:
```
The processing snippet is a function which receives a payload as an argument.
```

I see we could mention that the value needs to be a function in a few places, but it feels quite clear to me considering there is [an example](https://docs.api3.org/reference/ois/latest/processing.html#example-3).

> Also the value fields in all OIS V2 processing-related tests would error. If those are just placeholders, which is fine, it should be clearer.

Yep, those should be changed.

**Comment by Siegrift** [comment]
Whoops, I didn't want to close this (but I did because I referenced the issue in a closing context).

@dcroote I am happy to implement/review any improvements :)

**Comment by dcroote** [comment]
> the value needs to be a function

This is what got me, but you're right there are a few examples. Let me think a little more

**Comment by dcroote** [comment]
I'm trying to understand a bit more on where we can clarify- the word "payload" appears frequently in [this section](https://docs.api3.org/reference/ois/latest/processing.html#input-and-output-1)- why this word choice?

**Comment by Siegrift** [comment]
I wanted to refer to "the thing passed to processing script" and they are fundamentally different for pre and post processing. TBH I can't think of a better work then payload. Maybe "initial value" but that may be confusing with pre/post processing v1 where you can chain these.

**Comment by dcroote** [comment]
> I wanted to refer to "the thing passed to processing script"

I agree it's pretty tricky to think of simple wording here. What about:

```diff
- The processing snippet is a function which receives a payload as an argument.
+ The processing snippet expects a function that takes an object as an argument, the properties of which are different for pre-processing and post-processing.
```

**Comment by Siegrift** [comment]
Yeah, I think that is a bit clearer.
