### ISSUE TITLE
dAPI chains list inconsistent with Market

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#760]
The [dAPI Chains and Contracts page](https://docs.api3.org/reference/dapis/chains/) lists chains that aren't supported by the Market. This is because the axios build script includes the chain so long as the [Api3ServerV1 contract is present](https://github.com/api3dao/vitepress-docs/blob/3d9f63521dee7968d55f5a8c7529ab2223763709/libs/axiosBuildScripts.js#L32) within the [contracts repo addresses.json file](https://github.com/api3dao/vitepress-docs/blob/3d9f63521dee7968d55f5a8c7529ab2223763709/libs/axiosBuildScripts.js#L15). This results in chains like Rootstock (chain ID 30) being present when it is not on the Market.

Proposed solution: only include chains belonging to the `Api3Market` object of the [address.json file](https://raw.githubusercontent.com/api3dao/contracts/main/deployments/addresses.json).

**Comment by wkande** [comment]
That would work I beleive. Also there is `@api3/contract` but that would require a code update every time it changes.
