### ISSUE TITLE
Contract addresses are not current

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#790]
See the contract list page:
https://docs.api3.org/reference/airnode/latest/

There are chains that are no longer supported. These lists are auto generated but seem to have fallen out of sync.

**Comment by dcroote** [comment]
I'm a little confused by "supported" given your link to the Airnode contracts page. Do you mean the chain is no longer producing blocks or something else?

**Comment by wkande** [comment]
Just seems like some of the chains listed are legacy like Arbitrum Nova. Maybe they are still listed because the contract was put there at one time.

**Comment by dcroote** [comment]
> Maybe they are still listed because the contract was put there at one time.

Yes I think this is the reason. Is nova decommissioned? Any others you notice are decommissioned? If so, would make sense to remove them from Airnode then this docs list will automatically update.

**Comment by wkande** [comment]
I will take a deeper dive into this soon and see what I can come up with.

**Comment by wkande** [comment]
I reviewed the Azio script and remove support for the dAPI pages that were removed. Everything is up-to-date. See PR https://github.com/api3dao/vitepress-docs/pull/851
