### ISSUE TITLE
v0.14 airnode reference redirect not working

### ISSUE THREAD

**Issue by dcroote** [api3dao/vitepress-docs#812]
This v0.13 URL works fine:

https://docs.api3.org/reference/airnode/v0.13/docker/deployer-image.html#cloud-provider-credentials

This v0.14 URL (which should redirect to latest, no?) does not:

https://docs.api3.org/reference/airnode/v0.14/docker/deployer-image.html#cloud-provider-credentials

**Comment by wkande** [comment]
Will try to create a redirect of `/0.14` to `/latest`. Not sure how to do so but there must be a way.

**Comment by wkande** [comment]
No one has ask for redirects with the new version of `airnode-docs` so I am closing this issue. See PR: https://github.com/api3dao/vitepress-docs/pull/851
