### ISSUE TITLE
DAO Proposal guide

### ISSUE THREAD

**Issue by wkande** [api3dao/vitepress-docs#93]
There is a need to update the guide for the creation of a DAO proposal. Mark has/is creating a Google doc with some insight on how to improve the existing guide.

**Comment by wkande** [comment]
Heiki mentioned to be sure that proposals go into "Official Proposals".

**Comment by KenCarvAPI** [comment]
Did this get picked up

**Comment by wkande** [comment]
Mark did not reply. Am closing this issue.
